### PR TITLE
Fixes broken link

### PR DESCRIPTION
**Pull request by thejimbirch**
Was linking to the `dev `branch which looks like it no longer exists.  I know there is a ticket to switch from `master `to `main`, so I updated the link to go to the 2.x branch.

### CODE REVIEW

**Review by ModulesUnraveled — CHANGES_REQUESTED** [review]
Hey Jim! Thanks for this!

I know we're planning to switch from master to main at some point (hopefully sooner than later!) But I think `main` would still be the right branch to use for this.

The 2.x branch doesn't have any of the latest stuff in it. I think this particular file is identical between 2.x and master, but when we do eventually make the branch name switch, we'll have a task to update all docs currently pointing to master anyway, so it would be updated at that time.

If we use 2.x, I'm afraid this one would get missed.

So, if you can switch it to main, I'll get this merged ASAP!

**Comment by thejimbirch** [comment]
Updated.

**Review by ModulesUnraveled — APPROVED** [review]
Looks good. Thanks!

**Comment by ModulesUnraveled** [comment]
Hmmm... Looks like when I loaded up the Gitbook last week and it said "Updating Gitbook" it put it on a new platform that doesn't seem to actually use this repo anymore... It looks like they've made it into a Saas thing. We should be fine since open source projects are free, but this merge didn't do anything.

I'm going to have to figure out how to allow community contributions. Blergh!

**Pull request merged**
